name: Build ImmortalWrt with Custom Plugins

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
        rsync unzip zlib1g-dev file wget python3 python3-venv swig \
        device-tree-compiler libelf-dev autoconf automake libtool autopoint

    - name: Clone OpenClash
      run: |
        git clone --depth=1 https://github.com/vernesong/OpenClash.git package/OpenClash

    - name: Clone AdGuardHome
      run: |
        git clone --depth=1 https://github.com/rufengsuixing/luci-app-adguardhome.git package/luci-app-adguardhome

    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Download package
      run: make defconfig && make download -j8

    - name: Compile firmware
      run: make -j$(nproc) V=s

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: bin/targets/
