name: Build ImmortalWrt with Custom Plugins

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget python3

    - name: Clone OpenClash
      run: |
        git clone --depth=1 https://github.com/vernesong/OpenClash.git package/OpenClash

    - name: Clone AdGuardHome
      run: |
        git clone --depth=1 https://github.com/rufengsuixing/luci-app-adguardhome.git package/luci-app-adguardhome

    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Config plugins
      run: |
        cp feeds.conf.default feeds.conf.backup
        # 可以根据需要编辑feeds.conf.default，添加第三方源
        # 自动生成.config，如果你有现成的.config可以上传替换掉
        cat >> .config <<EOF
        CONFIG_PACKAGE_luci-app-upnp=y
        CONFIG_PACKAGE_luci-app-adguardhome=y
        CONFIG_PACKAGE_luci-app-openclash=y
        CONFIG_PACKAGE_luci-app-serverchan=y
        EOF

    - name: Download package
      run: make defconfig && make download -j8

    - name: Compile firmware
      run: make -j$(nproc) V=s
